import Augmentor
p = Augmentor.Pipeline("F:/augmentImages/Loose Silky-bent")
p.rotate90(probability=0.5)
p.rotate270(probability=0.5)
p.rotate180(probability=0.5)
p.flip_left_right(probability=0.8)
p.flip_top_bottom(probability=0.8)
p.skew_corner(probability=0.5)
p.skew_tilt(probability=0.5)
p.shear(probability=0.5,max_shear_left=20,max_shear_right=20)
p.greyscale(0.3)
p.random_brightness(0.3,0.9,1.1)
#p.crop_centre(probability=0.5,percentage_area=0.8)
p.sample(20000)
print(p)